nginx:
    image: tutum/nginx
    ports:
        - "8080:80"
    links:
        - phpfpm
        - mysql
    volumes:
        - ./default:/etc/nginx/sites-available/default
        - ./default:/etc/nginx/sites-enabled/default
        - ./logs/nginx-error.log:/var/log/nginx/error.log
        - ./logs/nginx-access.log:/var/log/nginx/access.log
        - ./www:/usr/share/nginx/html
phpfpm:
    image: php-ext
    ports:
        - "9000:9000"
    volumes:
        - ./www:/usr/share/nginx/html
    links:
        - mysql
mysql:
  image: mariadb
  volumes:
      - ./db-data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: ""
  ports:
    - "3306:3306" 

