version: '2'

services:
    db:
      image: mariadb
      container_name: ps-db
      volumes:
        - ./db-data:/var/lib/mysql
      environment:
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: "admin"
      ports:
        - "3306:3306" 

    prestashop:
      image: prestashop/prestashop:1.6.1.12
      container_name: ps
      depends_on:
        - db
      ports:
        - "8080:80"
      volumes:
        - ./logs/error.log:/var/log/apache2/error.log
        - ./logs/access.log:/var/log/apache2/access.log
        - ./www:/var/www/html




