version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ""
       MYSQL_DATABASE: bicishop
       MYSQL_USER: root

   prestashop:
     depends_on:
       - db
     image: prestashop/prestashop:1.6.1.12
     volumes:
       - ./themes:/var/www/html/themes
     ports:
       - "9000:80"
     restart: always

volumes:
    db_data:


